// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wordki.Bff.Migrations.Contexts;

#nullable disable

namespace Wordki.Bff.Migrations.Migrations
{
    [DbContext(typeof(AppMigrationDbContext))]
    [Migration("20260406201035_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wordki.Bff.SharedKernel.Events.SharedEventMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at_utc");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer_name");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("data_type");

                    b.Property<DateTime?>("HandledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("handled_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("PublisherName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("publisher_name");

                    b.HasKey("Id");

                    b.HasIndex("AddedAtUtc");

                    b.HasIndex("HandledAtUtc");

                    b.ToTable("shared_event_messages", "users");
                });

            modelBuilder.Entity("Wordki.Modules.Cards.Domain.Entities.Card", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BackSideId")
                        .HasColumnType("bigint")
                        .HasColumnName("back_side_id");

                    b.Property<long>("FrontSideId")
                        .HasColumnType("bigint")
                        .HasColumnName("front_side_id");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.HasKey("Id");

                    b.HasIndex("BackSideId")
                        .IsUnique();

                    b.HasIndex("FrontSideId")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.ToTable("cards", "cards");
                });

            modelBuilder.Entity("Wordki.Modules.Cards.Domain.Entities.CardSide", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("example");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.HasKey("Id");

                    b.ToTable("card_sides", "cards");
                });

            modelBuilder.Entity("Wordki.Modules.Cards.Domain.Entities.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BackSideType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("back_side_type");

                    b.Property<string>("FrontSideType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("front_side_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("groups", "cards");
                });

            modelBuilder.Entity("Wordki.Modules.Cards.Domain.Entities.Result", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CardSideId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_side_id");

                    b.Property<int>("Counter")
                        .HasColumnType("integer")
                        .HasColumnName("counter");

                    b.Property<int>("Drawer")
                        .HasColumnType("integer")
                        .HasColumnName("drawer");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<DateTime?>("NextRepeatUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_repeat_utc");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CardSideId")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("results", "cards");
                });

            modelBuilder.Entity("Wordki.Modules.Cards.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ExternalUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId")
                        .IsUnique();

                    b.ToTable("users", "cards");
                });

            modelBuilder.Entity("Wordki.Modules.Lessons.Domain.Entities.Lesson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("LessonKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lesson_kind");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer")
                        .HasColumnName("word_count");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("lessons", "lessons");
                });

            modelBuilder.Entity("Wordki.Modules.Lessons.Domain.Entities.LessonRepetition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AnsweredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at_utc");

                    b.Property<bool>("IsKnown")
                        .HasColumnType("boolean")
                        .HasColumnName("is_known");

                    b.Property<long>("LessonId")
                        .HasColumnType("bigint")
                        .HasColumnName("lesson_id");

                    b.Property<long>("QuestionResultId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_result_id");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("QuestionResultId");

                    b.HasIndex("LessonId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("lesson_repetitions", "lessons");
                });

            modelBuilder.Entity("Wordki.Modules.Lessons.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ExternalUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_user_id");

                    b.HasKey("Id")
                        .HasName("PK_users1");

                    b.HasIndex("ExternalUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_users_external_user_id1");

                    b.ToTable("users", "lessons");
                });

            modelBuilder.Entity("Wordki.Modules.Users.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailConfirmationTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("EmailConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("PK_users2");

                    b.HasIndex("DeletedAtUtc");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("users", "users");
                });

            modelBuilder.Entity("Wordki.Modules.Cards.Domain.Entities.Card", b =>
                {
                    b.HasOne("Wordki.Modules.Cards.Domain.Entities.CardSide", "BackSide")
                        .WithOne("CardWhereBack")
                        .HasForeignKey("Wordki.Modules.Cards.Domain.Entities.Card", "BackSideId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wordki.Modules.Cards.Domain.Entities.CardSide", "FrontSide")
                        .WithOne("CardWhereFront")
                        .HasForeignKey("Wordki.Modules.Cards.Domain.Entities.Card", "FrontSideId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wordki.Modules.Cards.Domain.Entities.Group", "Group")
                        .WithMany("Cards")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackSide");

                    b.Navigation("FrontSide");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Wordki.Modules.Cards.Domain.Entities.Group", b =>
                {
                    b.HasOne("Wordki.Modules.Cards.Domain.Entities.User", null)
                        .WithMany("Groups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Wordki.Modules.Cards.Domain.Entities.Result", b =>
                {
                    b.HasOne("Wordki.Modules.Cards.Domain.Entities.CardSide", "CardSide")
                        .WithOne("Result")
                        .HasForeignKey("Wordki.Modules.Cards.Domain.Entities.Result", "CardSideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wordki.Modules.Cards.Domain.Entities.User", "User")
                        .WithMany("Results")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardSide");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wordki.Modules.Lessons.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("Wordki.Modules.Lessons.Domain.Entities.User", "User")
                        .WithMany("Lessons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wordki.Modules.Lessons.Domain.Entities.LessonRepetition", b =>
                {
                    b.HasOne("Wordki.Modules.Lessons.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Repetitions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Wordki.Modules.Cards.Domain.Entities.CardSide", b =>
                {
                    b.Navigation("CardWhereBack");

                    b.Navigation("CardWhereFront");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Wordki.Modules.Cards.Domain.Entities.Group", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Wordki.Modules.Cards.Domain.Entities.User", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Wordki.Modules.Lessons.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("Repetitions");
                });

            modelBuilder.Entity("Wordki.Modules.Lessons.Domain.Entities.User", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
